library(Biostrings)
library(bio3d)
library(dplyr)
library(readr)
library(purrr)

HShr122 <- DNAString("TTATTACACGAAACTCAAGCACATGTAGATGATGCCCATCATGCTCATCATGTAGCCGATGCCCATCATGCTCATCATGTAGCCGATGCCCATCATGCTCATCATGCAGCCGATGCCCATCATGCTCATCATGCAGCCGATGCCCATCATGCTCATCATGCAGCCTATGCCCATCATGCTCATCATGCAGCCGATGCTCACCATGCAACCGATGCTCATCATGCAGCCGATGCTCACCATGCAGCCGATGCTCACCATGCAACCGATGCTCATCACGCTCATCATGCAGCCGATGCCCATCACGCTCACCATGCAGCCGATGCTCATCAYGCTCATCATGCAGCCGATGCCCATCATGCTCATCATGCAGCCGATGCCCATCATGCTCATCATGCAGCCGATGCCCATCATGCTCACCATGCAGCTGATGCTCATCACGCTCATCATGCAGCCGATGCCCATCATGCTCATCATGCAGCCTATGCCCATCATGCTCATCATGCATCCGATGCTCATCATGCAGCTGATGCTCACCATGCAGCTTATGCCCATCACGCTCATCATGCAGCTGATGCTCATCATGCAGCCGATGCTCACCATGCAACCGATGCTCATCACGCTCACCATGCAGCCGATGCTCACCATGCAACCGATGCTCATCATGCAGCCGATGCTCACCATGCAGCCGATGCTCACCATGCAGCCGATGCTCATCATGCAGCCGCACACCATGCAACTGATGCTCACCATGCAGCCGCACACCATGCAACCGATG")

HShr122_aa <- translate(HShr122, if.fuzzy.codon="solve")

motifs <- read_csv("AA_Repeats.csv")
# type4_motif <- c("AHH")
# 
# map(motifs$AA_Repeats, function(x) length(motif.find(x, HShr122_aa)))
# 
# length(motif.find(type4_motif, HShr122_aa))


count_motifs <- function(data, motifs, motif_column = NULL, name_column = NULL){
  motif_list <- motifs[[motif_column]]
  motif_names <- motifs[[name_column]]
  
  output <- map(motif_list, function(x) length(motif.find(x, data))) %>% 
    as.data.frame()
  
  colnames(output) <- paste0(name_column, "_", motif_names)
  return(output)
}

## Test
count_motifs(data = HShr122_aa, motifs = motifs, motif_column = "AA_Repeats", name_column = "Type")
